### ISSUE TITLE
Block Comments Not started at first of line

### ISSUE THREAD

**Issue by MtneerInTN** [tshort/opendss-vscode#1]
Hi,
I'm writing an OpenDSS parser to visualize some aspects of an OpenDSS circuit.  When handling block comments I noticed...
![image](https://user-images.githubusercontent.com/13684227/210148744-b775ce69-4934-4aac-b2ff-9de94b544716.png)

new circuit.IEEE13Nodeckt  !strip this part from chunk
More basekv=115 pu=1.0001 phases=3 bus1=SourceBus  !test More instead of ~
~ test parser /* worst case
would be
if this */ ~ack
~ Angle=30                                                         ! advance angle 30 deg so result agree with published angle
~ MVAsc3=20000 MVASC1=21000    ! stiffen the source to approximate inf source

is colored as a legal block comment, but the manual says block comments have to start a line?  

/* … */ Block Comments
New at version 7.6, you can now comment out whole sections (whole lines of script) using the
block comment capability. The block comment must begin with /* in the FIRST column of the
line. The block comment terminates after the appearance of */ anywhere in a line or with the
end of a script file or selection in a script window. Example:
Compile "C:\Users\prdu001\DSSData\CDR\Master3.DSS"
New Monitor.Line1-PQ Line.LINE1 1 mode=1 ppolar=no
New Monitor.Line1-VI Line.LINE1 1 mode=0 VIpolar=Yes
/* comment out the next two monitors
New Monitor.Source-PQ Vsource.source 1 mode=1 ppolar=no
New Monitor.source-VI Vsource.source 1 mode=0 VIpolar=Yes
****/ End of block comment

**Comment by MtneerInTN** [comment]
![image](https://user-images.githubusercontent.com/13684227/210148927-31a0e203-e18a-4088-957b-e2a2571b66b8.png)

**Comment by MtneerInTN** [comment]
OpenDSS Manual
Program Revision: 9.0.0, Build 3+ June 2020

**Comment by tshort** [comment]
I didn't know that. Interesting. [This line](https://github.com/tshort/opendss-vscode/blob/3d51cb0f2ebcf3f8a4f7fb480d92cee85f7cde77/syntaxes/opendss.tmLanguage.json#L53) probably needs to be tweaked.

**Comment by PMeira** [comment]
Yeah, from [the relevant loop from the OpenDSS code](https://github.com/dss-extensions/dss_capi/blob/0.13.1/src/Executive/ExecHelper.pas#L546-L570):

```pascal
                        // in block comment ... look for */   and cancel block comment (whole line)
                        if InBlockComment then
                            if Pos('*/', Inputline) > 0 then
                                InBlockComment := FALSE;
```

> I didn't know that. Interesting. [This line](https://github.com/tshort/opendss-vscode/blob/3d51cb0f2ebcf3f8a4f7fb480d92cee85f7cde77/syntaxes/opendss.tmLanguage.json#L53) probably needs to be tweaked.

Changing that to `"end": "\\*/.*",` seems to be enough.

Another issue I noticed is that neither the third nor the fourth lines here are matched as comments:

```
new capacitor.6  phases=3 kv=23 conn=wye bus1= 6 kvar=1200
// new capacitor.9  phases=3 kv=23 conn=wye bus1= 9 kvar=1200
//new capacitor.9  phases=3 kv=23 conn=wye bus1= 9 kvar=1200
/*new line.3_13  phases=3 length=5.29 bus1= 3 bus2=13 r1=0.11  x1=0.11
new line.13_14 phases=3 length=5.29 bus1=13 bus2=14 r1=0.09  x1=0.12
new line.13_15 phases=3 length=5.29 bus1=13 bus2=15 r1=0.08  */ x1=0.11
```

Moving the `#comments` include to the start seems to be enough to fix that.
I'll open a PR soon with these changes.

There are more complicated issues but at that point we could use a language server, since a lot in OpenDSS is context-sensitive. That's why is usually not the best idea to write custom parsers. I guess it's a good idea to finish the JSON exports for DSS Extensions so we can recommend people use that instead (currently we have partial support [like these](https://dss-extensions.org/OpenDSSDirect.jl/latest/search/?q=json)).

**Comment by tshort** [comment]
The JSON export is an interesting idea. I'm not sure it helps with regular input files, though. JSON is great for data interchange, but it seems like trouble when using as a human-editable input file (verbose, easy to mess up brackets and quotes).

**Comment by PMeira** [comment]
@tshort Yes, for input, especially smaller circuits or incremental changes (like loading a large circuit and inserting something extra), I think the DSS scripts do a good job. If we had a language server, it would be great; if nobody looks into that, I'll probably handle it eventually. 

Something I plan to work a bit more is Jupyter integration. Since DSS Python currently supports most plots (pending some fixes and tests), it's a good environment to explore OpenDSS. I added a `%%dss` cell magic there to accept script snippets directly, but it's missing proper highlighting. When it gets more mature, it'd be nice to port to ODD.jl as most of the tooling related to Jupyter would be shared.

JSON would be more for interchange indeed, especially for extracting the DSS circuit already parsed without needing to worry about all corner cases of the parser and all the side-effects from the property system. Reading JSON for input would be easy too, yet for reading from DBs or converting from other sources on the fly, the batch API should be enough:
https://github.com/dss-extensions/dss_python/blob/0.13.1/tests/test_batch.py#L265

I should finish some work related to that by the end of the month (some of it is specific to Brazil). Later, most of the interesting results should move down to the engine to be shared with all languages without needing to reimplement, test, and maintain disparate implementations.
